### ISSUE TITLE
`cake build` complains about missing jquery

### ISSUE THREAD

**Issue by srid** [stephank/orona#10]
```
$ cake build

/Users/sridharr/orona/Cakefile:35
        throw e;
        ^
Error: ENOENT, No such file or directory 'vendor/jquery-ui-1.8.8.zip'
    at Object.statSync (fs.js:366:18)
    at /Users/sridharr/orona/Cakefile:31:10
    at Object.action (/Users/sridharr/orona/Cakefile:129:18)
    at /Users/sridharr/.nvm/v0.4.0/lib/node/.npm/coffee-script/1.0.1/package/lib/cake.js:31:26
    at Object.action (/Users/sridharr/orona/Cakefile:191:5)
    at /Users/sridharr/.nvm/v0.4.0/lib/node/.npm/coffee-script/1.0.1/package/lib/cake.js:31:26
    at /Users/sridharr/.nvm/v0.4.0/lib/node/.npm/coffee-script/1.0.1/package/lib/cake.js:53:23
    at path.js:271:19
```

**Comment by stephank** [comment]
Thanks for reporting the issue.

I'm looking at a bunch of compatibility problems that have cropped up in the code since Node 0.4 and NPM 1.0, including this one. I'll make a release once I've got everything working again.

**Comment by stephank** [comment]
FWIW, this is pending on a fix for: https://github.com/isaacs/npm/issues/890

Sorry if this is keeping you.

**Comment by stephank** [comment]
I upgraded the whole stack of dependencies, and this is fixed at least.

(Though don't be surprised if I've broken other stuff in the process. Only had time for a quick test.)
