### ISSUE TITLE
Refactoring required

### ISSUE THREAD

**Issue by rpavez** [stephank/orona#12]
I had fun playing with the demo and taught about adding more elements but discovered that versions of dependencies are nearly deprecated (specially node version). It is important to refactor the code to update the code in order to work with latest stable versions of dependencies and enable community use and work on this project.

`"engines: ": {
    "node": "0.4"
  },
  "dependencies": {
    "coffee-script": "1",
    "villain": "=0.2.0",
    "faye-websocket": "0.3",
    "connect": "1.8",
    "irc-js": "0.2",
    "browserify": "1.9"
  },`

**Comment by stephank** [comment]
Thanks for reporting this! I think I intended this to say `">=0.4"`, but now changed it to `"0.6"`, because that's the only version I'm testing on. Updated the other deps while I was at it.
